on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ci_pat }}
          submodules: "recursive"

