name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] # TODO: macos-11
      fail-fast: false
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - uses: hendrikmuhs/ccache-action@v1
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-11'

      - name: Get short git SHA
        id: sha
        run: echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install system dependencies (Ubuntu)
        run: ./scripts/install_deps_ubuntu.sh
        if: matrix.os == 'ubuntu-20.04'

      - name: Install system dependencies (Mac)
        run: ./scripts/install_deps_mac.sh
        if: matrix.os == 'macos-11'

      - name: Install venv dependencies
        run: ./bootstrap_venv.sh

      - name: Create and upload release
        run: |
          TAG=v.$(git rev-parse --short HEAD)
          git tag $TAG
          git push origin $TAG
          tar -czvf venv-${{ matrix.os }}.tar.gz venv
          gh release create $TAG
          gh release upload $TAG venv-${{ matrix.os }}.tar.gz
